services:
  smtp:
    build: .
    working_dir: /srv/smtp/data
    command: ["/usr/bin/smtp_server"]
    ports:
      - "25000:25000"
    volumes:
      - maildata:/srv/smtp/data

  imap:
    build: .
    working_dir: /srv/smtp/data
    command: ["/usr/bin/imap_server", "/srv/smtp/"]
    ports:
      - "2553:2553"
    volumes:
      - maildata:/srv/smtp/data

  seed-users:
    build: .
    command: ["/usr/bin/mua_seed_users", "/srv/smtp/"]
    volumes:
      - maildata:/srv/smtp/data
    restart: "no"
    profiles: ["tools"]

  seed-stress-users:
    build: .
    command: ["/usr/bin/mua_seed_stress_users", "/srv/smtp/", "20"]
    volumes:
      - maildata:/srv/smtp/data
    restart: "no"
    profiles: ["tools"]

  delete-stress-users:
    build: .
    command: ["/usr/bin/mua_delete_stress_users", "/srv/smtp/"]
    volumes:
      - maildata:/srv/smtp/data
    restart: "no"
    profiles: ["tools"]

volumes:
  maildata:
