#pragma once
#include <string_view>

// Generated by xxd -i from scheme/001_init_scheme.sql
extern "C" {
extern unsigned char init_schema_sql[];
extern unsigned int init_schema_sql_len;
}

inline std::string_view initSchema() {
    return {reinterpret_cast<const char*>(init_schema_sql), init_schema_sql_len};
}
