/* Generated by cbindgen — do not edit */

/* Maximum input size (15 MiB) */
#define SMTP_BASE64_MAX_SIZE ((size_t)(15 * 1024 * 1024))

#ifndef SMTP_BASE64_H
#define SMTP_BASE64_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>



#define SMTP_BASE64_OK 0

#define SMTP_BASE64_EBUFSZ -1

#define SMTP_BASE64_ETOOLARGE -2

#define SMTP_BASE64_EINVAL -3

#define SMTP_BASE64_ENULL -4

typedef struct SmtpStreamDecoder SmtpStreamDecoder;

typedef struct SmtpStreamEncoder SmtpStreamEncoder;

uintptr_t smtp_base64_encode_len(uintptr_t in_len);

int32_t smtp_base64_encode(const uint8_t *in_ptr,
                           uintptr_t in_len,
                           uint8_t *out_ptr,
                           uintptr_t *out_len);

uintptr_t smtp_base64_decode_len(uintptr_t in_len);

int32_t smtp_base64_decode(const uint8_t *in_ptr,
                           uintptr_t in_len,
                           uint8_t *out_ptr,
                           uintptr_t *out_len);

struct SmtpStreamEncoder *smtp_stream_encoder_new(void);

void smtp_stream_encoder_free(struct SmtpStreamEncoder *enc);

int32_t smtp_stream_encoder_feed(struct SmtpStreamEncoder *enc, const uint8_t *data, uintptr_t len);

int32_t smtp_stream_encoder_finalize(struct SmtpStreamEncoder *enc);

int32_t smtp_stream_encoder_take(struct SmtpStreamEncoder *enc,
                                 uint8_t *out_ptr,
                                 uintptr_t *out_len);

struct SmtpStreamDecoder *smtp_stream_decoder_new(void);

void smtp_stream_decoder_free(struct SmtpStreamDecoder *dec);

int32_t smtp_stream_decoder_feed(struct SmtpStreamDecoder *dec, const uint8_t *data, uintptr_t len);

int32_t smtp_stream_decoder_finalize(struct SmtpStreamDecoder *dec);

int32_t smtp_stream_decoder_take(struct SmtpStreamDecoder *dec,
                                 uint8_t *out_ptr,
                                 uintptr_t *out_len);

#endif  /* SMTP_BASE64_H */
